import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Privacy",
  description:
    "How VSP Innovations handles the information visitors share with VSP Connect founder profiles.",
};

const UPDATED = "22 September 2026";
const CONTACT = "privacy@vspinnovations.com";

export default function Privacy() {
  return (
    <main id="main" className="legal-main">
      <Link href="/" className="back-link">
        <ArrowLeft size={15} /> Our people
      </Link>
      <div className="legal-heading">
        <div className="eyebrow">VSP CONNECT · PRIVACY</div>
        <h1>What we collect, and why.</h1>
        <p>
          This page explains, in plain language, what happens to the information
          you share on a VSP Connect profile.
        </p>
        <p className="legal-updated">Last updated {UPDATED}</p>
      </div>

      <section className="legal-section">
        <h2>Who we are</h2>
        <p>
          VSP Connect is operated by VSP Innovations. We run the founder
          profiles on this site and the AI assistant on each of them.
        </p>
      </section>

      <section className="legal-section">
        <h2>What we collect</h2>
        <ul className="legal-list">
          <li>
            <strong>Your chat with a founder&rsquo;s AI assistant.</strong> The
            messages you send and the replies the assistant gives.
          </li>
          <li>
            <strong>Contact details you choose to share.</strong> If you ask us
            to follow up, we keep what you give us in the chat &mdash; your
            name, email, phone number or company.
          </li>
          <li>
            <strong>Anonymous usage events.</strong> Page views, contact saves
            and shares. We do not store any visitor identifier with these, only
            the hostname of the site you arrived from.
          </li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>Why we collect it</h2>
        <p>
          To answer your enquiry, to follow up with people who ask us to, and to
          understand which sharing channels actually bring people to a profile.
        </p>
      </section>

      <section className="legal-section">
        <h2>Who processes it</h2>
        <ul className="legal-list">
          <li>
            <strong>Supabase</strong> &mdash; our database.
          </li>
          <li>
            <strong>Anthropic</strong> &mdash; generates the AI assistant&rsquo;s
            answers from your message.
          </li>
          <li>
            <strong>Vercel</strong> &mdash; hosts the site.
          </li>
        </ul>
        <p>We do not sell your data.</p>
      </section>

      <section className="legal-section">
        <h2>About the AI assistant</h2>
        <p>
          Answers are generated by AI from information VSP Innovations has
          approved, and they may be imperfect. Please don&rsquo;t share
          sensitive personal information in the chat.
        </p>
      </section>

      <section className="legal-section">
        <h2>How long we keep it, and your requests</h2>
        <p>
          Chat messages and contact details are kept only as long as we need
          them to handle your enquiry. To see or delete the data we hold about
          you, email{" "}
          <a className="legal-link" href={`mailto:${CONTACT}`}>
            {CONTACT}
          </a>
          .
        </p>
      </section>
    </main>
  );
}
